version: "3.9"

services:
  golang-tg-bot:
    container_name: golang_tg_bot
    restart: always
    build: ./
    image: golang-tg-bot
    env_file:
      - bot.env
    depends_on:
      - postgres-db
    networks:
      - postgres

  postgres-db:
    image: postgres:15.5
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=itmo_delivery
    volumes:
      - postgres-db-data:/var/lib/postgresql/data
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:7.6
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@root.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgAdmin
    networks:
      - postgres
    depends_on:
      - postgres-db    

networks:
  postgres:
    driver: bridge

volumes:
  postgres-db-data:
  pgadmin-data:
